### ISSUE TITLE
Rename BAPS3?

### ISSUE THREAD

**Issue by MattWindsor91** [UniversityRadioYork/baps3-spec#1]
While BAPS3 will be the name of the URY implementation of this spec due to historical baggage, I think the actual name of the spec needs to be changed to something more approachable.

To get the ball rolling, here are some possibilities (mostly based on Norse mythology, because we're all based in York):
- `midgard` (**Mi**croservices **D**elivering **G**reat **A**udio for **R**a**d**io)--a very human set of userland tools for pushing audio around the place.
  - \+ Viking theme
  - \+ Backronym makes sense
  - \+ Exactly what it says on the tin
  - \- Backronym is a bit contrived and a bit unwieldy
  - \- Not a very catchy name
- `mjolnir` (**M**ultimedia **J**ob **O**peration-**L**evel **N**odes **I**ntended for **R**adio)--a hammer with which to drive in the nail of audio.
  - \+ Viking theme
  - \+ Sounds awesome and powerful
  - \- Very contrived backronym (like, seriously, wat)
- `bifrost` (**B**asic **I**nterfaces **F**or **R**adio-**O**riented **S**ound **T**ransfer)--magical rainbow bridge linking presenters to the music library
  - \+ Also Viking theme
  - \+ Vaguely relevant name?
  - \- Yes, this is contrived too

**Comment by wlcx** [comment]
![image](https://cloud.githubusercontent.com/assets/3065381/6096785/c0b7de4a-af9b-11e4-81c9-03396e79dfb6.png)

**Comment by MattWindsor91** [comment]
- `cougar` - Collection Of Utilities Guaranteeing Amazing Radio
- `spartan` - Systems/Protocols A Radio-station Transmitting Audio Needs
- `psiren` - [Protocol Specification Intended for Radio ENablement](http://en.wikipedia.org/wiki/Psirens)
- `spork` - Sound Protocols from York

**Comment by MattWindsor91** [comment]
wontfix (for now)
